# MAPP SERVER
mapp-root-host: "http://localhost:8080"


# AUTHENTICATION
# @ server-ip: "Your server host ip, like 127.0.0.1:25565"
# @ api-key: "Server's API key"
# You can get more information on our website
server-ip:
api-key:


# YOUR SERVER
# Delay between players data publishing in ticks (20 ticks = 1 second)
players-data-publish-period: 20
max-publish-attempts: 5