# MAPP SERVER
mapp-root-host: "http://localhost:8080"


# AUTHENTICATION
# @ server-ip: "Your server host ip, like 127.0.0.1:25565"
# @ api-key: "Server's API key"
# You can get more information on our website
username:
password:
client-id:
client-secret:


# YOUR SERVER
# Delay between players data publishing in ticks (20 ticks = 1 second)
publish-players-data: true
players-data-publish-period: 20

publish-regions-data: true
region-images-publish-period: 60

publish-server-info: true
server-info-publish-period: 120


# FORCE VISIBLE PLAYERS
# Players in this list will be force visible on MAP server
force-visible-players:
