name: mApp
version: ${project.version}
main: me.bogger.mapp.Main
api-version: 1.16
authors: [ Bogger ]
description: None
website: None
commands:
  force-visible:
    description: Makes player visible to everybody on the MAPP server
    usage: /<command> true/false
    aliases: None
  publish-all-regions:
    description: Loads all regions of specific world to MAPP server
    usage: /<command> world-name
    aliases: None